# sitemap settings

template: sitemap.twig
xml_template: sitemap_xml.twig

ignore:
  - /page/home
  - /page/error404
  - /page/private
  - /news/.*

## ignore by "slug" of contenttype
#ignore_contenttype:
#  - pages

## ignore listing templates
#ignore_listing: true
